### ISSUE TITLE
Create HTML template for Log Work (zadat práci)

### ISSUE THREAD

**Issue by Tondakozak** [BaraT91/Cesnek-admin#10]
Create HTML template for Log Work page

The page should be static, with just example data hard-coded in HTML.

Do not implement dialog windows with other forms.

It would be nice if components (form fields, table...) are created as React components. Please coordinate with other task.

Don't spend too much time working on CSS. Make pull requests often.

![obrazek](https://github.com/BaraT91/Cesnek-admin/assets/25927335/9feb6653-a2b3-47c8-9f2d-9099183e18cd)

**Comment by BaraT91** [comment]
Done
